# Generated by Django 3.2.1 on 2021-05-07 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210507_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 12, 55, 55, 298623, tzinfo=utc)),
        ),
    ]
